name: Gigs
modelClass: MalcolmLevon\Gigs\Models\Gigs
form: $/malcolmlevon/gigs/models/gigs/fields.yaml
defaultRedirect: malcolmlevon/gigs/gigs
create:
    redirect: 'malcolmlevon/gigs/gigs/update/:id'
    redirectClose: malcolmlevon/gigs/gigs
update:
    redirect: malcolmlevon/gigs/gigs
    redirectClose: malcolmlevon/gigs/gigs
