name: Venue
modelClass: MalcolmLevon\Gigs\Models\Venue
form: $/malcolmlevon/gigs/models/venue/fields.yaml
defaultRedirect: malcolmlevon/gigs/venue
create:
    redirect: 'malcolmlevon/gigs/venue/update/:id'
    redirectClose: malcolmlevon/gigs/venue
update:
    redirect: malcolmlevon/gigs/venue
    redirectClose: malcolmlevon/gigs/venue
