title: Venue
modelClass: MalcolmLevon\Gigs\Models\Venue
list: $/malcolmlevon/gigs/models/venue/columns.yaml
recordUrl: 'malcolmlevon/gigs/venue/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
