name: Artist
modelClass: MalcolmLevon\Gigs\Models\Artist
form: $/malcolmlevon/gigs/models/artist/fields.yaml
defaultRedirect: malcolmlevon/gigs/artist
create:
    redirect: 'malcolmlevon/gigs/artist/update/:id'
    redirectClose: malcolmlevon/gigs/artist
update:
    redirect: malcolmlevon/gigs/artist
    redirectClose: malcolmlevon/gigs/artist
